-- ==========================================================================
-- SUPABASE DATABASE SCHEMA FOR ILFA 10TH BATCH UNION WEBSITE
-- Copy and paste this code into your Supabase SQL Editor and click 'Run'.
-- ==========================================================================

-- 1. Create Tags Table
create table tags (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text unique not null
);

-- 2. Create News & Events Table
create table news (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  "desc" text not null,
  date date not null,
  image_url text not null,
  tag text not null,
  is_featured boolean default false not null,
  sort_order integer default 0 not null
);

-- 3. Create Achievements Table
create table achievements (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  pos text not null, -- Position or Qualification
  "desc" text not null,
  image_url text not null
);

-- 4. Enable Row Level Security (RLS)
alter table tags enable row level security;
alter table news enable row level security;
alter table achievements enable row level security;

-- 5. Create Public Read & Write Access Policies (RLS Bypass for Anon Key)
-- These policies permit anonymous public access for prototyping without user authentication.

-- Policies for Tags
create policy "Allow public read access to tags" on tags for select using (true);
create policy "Allow public insert access to tags" on tags for insert with check (true);
create policy "Allow public update access to tags" on tags for update using (true);
create policy "Allow public delete access to tags" on tags for delete using (true);

-- Policies for News
create policy "Allow public read access to news" on news for select using (true);
create policy "Allow public insert access to news" on news for insert with check (true);
create policy "Allow public update access to news" on news for update using (true);
create policy "Allow public delete access to news" on news for delete using (true);

-- Policies for Achievements
create policy "Allow public read access to achievements" on achievements for select using (true);
create policy "Allow public insert access to achievements" on achievements for insert with check (true);
create policy "Allow public update access to achievements" on achievements for update using (true);
create policy "Allow public delete access to achievements" on achievements for delete using (true);

-- ==========================================================================
-- 6. Create Settings Table for Homepage Configurations
-- ==========================================================================
create table settings (
  key text primary key,
  value jsonb not null
);

-- Enable Row Level Security (RLS)
alter table settings enable row level security;

-- Policies for Settings
create policy "Allow public read access to settings" on settings for select using (true);
create policy "Allow public insert access to settings" on settings for insert with check (true);
create policy "Allow public update access to settings" on settings for update using (true);
create policy "Allow public delete access to settings" on settings for delete using (true);

-- ==========================================================================
-- 7. Seed Default Tag Categories
-- ==========================================================================
insert into tags (name) values
  ('Qatar Hadia'),
  ('Bookplus'),
  ('Achievements'),
  ('General')
on conflict (name) do nothing;

-- ==========================================================================
-- 8. Create Committee Table
-- ==========================================================================
create table committee (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  place text not null,
  position text not null,
  image_url text not null
);

-- Enable Row Level Security (RLS)
alter table committee enable row level security;

-- Policies for Committee
create policy "Allow public read access to committee" on committee for select using (true);
create policy "Allow public insert access to committee" on committee for insert with check (true);
create policy "Allow public update access to committee" on committee for update using (true);
create policy "Allow public delete access to committee" on committee for delete using (true);


